[package]
name = "mediasoup"
version = "0.8.3"
description = "Cutting Edge WebRTC Video Conferencing in Rust"
categories = ["api-bindings", "multimedia", "network-programming"]
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
license = "ISC"
keywords = ["webrtc", "ortc", "sfu"]
documentation = "https://docs.rs/mediasoup"
repository = "https://github.com/versatica/mediasoup"
readme = "README.md"
include = [
    "/src",
    "/README.md"
]

[package.metadata.docs.rs]
default-target = "x86_64-unknown-linux-gnu"
targets = []

[dependencies]
async-channel = "1.6.1"
async-executor = "1.4.1"
async-fs = "1.5.0"
async-io = "1.6.0"
async-lock = "2.4.0"
async-oneshot = "0.5.0"
async-trait = "0.1.50"
bytes = "1.0.1"
event-listener-primitives = "1.0.0"
fastrand = "1.5.0"
futures-lite = "1.12.0"
h264-profile-level-id = "0.1.1"
log = "0.4.14"
libc = "0.2.98"
once_cell = "1.8.0"
serde_json = "1.0.64"
serde_repr = "0.1.7"
thiserror = "1.0.26"

[dependencies.lru]
default-features = false
version = "0.6.5"

[dependencies.mediasoup-sys]
path = "../worker"
version = "0.2.4"

[dependencies.parking_lot]
version = "0.11.1"
features = ["serde"]

[dependencies.regex]
default-features = false
features = ["std", "perf"]
version = "1.5.4"

[dependencies.serde]
features = ["derive"]
version = "1.0.126"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.8.2"

[dev-dependencies]
actix = "0.12.0"
actix-web = "4.0.0-beta.8"
actix-web-actors = "4.0.0-beta.6"
env_logger = "0.9.0"
