name: mediasoup-worker

on: [push, pull_request]

concurrency:
  # Cancel a currently running workflow from the same PR, branch or tag when a
  # new workflow is triggered.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        build:
          - os: ubuntu-20.04
            cc: gcc
            cxx: g++
          - os: ubuntu-20.04
            cc: clang
            cxx: clang++
          - os: ubuntu-22.04
            cc: gcc
            cxx: g++
          - os: ubuntu-22.04
            cc: clang
            cxx: clang++
          - os: macos-12
            cc: gcc
            cxx: g++
          - os: macos-12
            cc: clang
            cxx: clang++
          - os: windows-2022
            cc: cl
            cxx: cl
        # A single Node.js version should be fine for C++.
        node:
          - 20

    runs-on: ${{ matrix.build.os }}

    env:
      CC: ${{ matrix.build.cc }}
      CXX: ${{ matrix.build.cxx }}
      MEDIASOUP_SKIP_WORKER_PREBUILT_DOWNLOAD: 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ matrix.build.os }}-node-${{matrix.build.cc}}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ matrix.build.os }}-node-${{matrix.build.cc}}-

      # TODO: TMP: REMOVE
      - name: python3 --version
        run: python3 --version

      # TODO: TMP: REMOVE
      - name: pip3 --version
        run: pip3 --version

      # We need to install some NPM production deps for npm-scripts.mjs to work.
      - name: npm ci
        run: npm ci --ignore-scripts --omit=dev

      # However we also need to install pip invoke by manually invoking the NPM
      # 'preinstall' script (since `--ignore-scripts` above made it not run).
      - name: npm run preinstall
        run: npm run preinstall

      # We need to install deps on worker/scripts/package.json.
      - name: npm run install-worker-dev-tools
        run: npm run install-worker-dev-tools
        # TODO: Maybe fix this one day.
        if: runner.os != 'Windows'

      - name: npm run lint:worker
        run: npm run lint:worker
        # TODO: Maybe fix this one day.
        if: runner.os != 'Windows'

      - name: npm run worker:build
        run: npm run worker:build

      - name: npm run test:worker
        run: npm run test:worker
        # TODO: Maybe fix this one day.
        if: runner.os != 'Windows'
