name: mediasoup-worker

on: [push, pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        build:
          - os: ubuntu-18.04
            cc: gcc
            cxx: g++
          - os: ubuntu-18.04
            cc: clang
            cxx: clang++
          - os: ubuntu-20.04
            cc: gcc
            cxx: g++
          - os: ubuntu-20.04
            cc: clang
            cxx: clang++
          - os: macos-10.15
            cc: gcc
            cxx: g++
          - os: macos-10.15
            cc: clang
            cxx: clang++
          - os: macos-11
            cc: gcc
            cxx: g++
          - os: macos-11
            cc: clang
            cxx: clang++
          - os: windows-2019
            cc: cl
            cxx: cl
          - os: windows-2022
            cc: cl
            cxx: cl
        # A single Node.js version should be fine for C++.
        node:
          - 14

    runs-on: ${{ matrix.build.os }}

    env:
      CC: ${{ matrix.build.cc }}
      CXX: ${{ matrix.build.cxx }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm run install-clang-tools
        # TODO: Maybe fix this one day.
        if: runner.os != 'Windows'
      - run: npm run lint:worker
        # TODO: Maybe fix this one day.
        if: runner.os != 'Windows'

      - name: Configure cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ matrix.build.os }}-node-${{matrix.build.cc}}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ matrix.build.os }}-node-${{matrix.build.cc}}-

      - run: npm run worker:build
      - run: npm run test:worker
        if: runner.os != 'Windows'
