name: mediasoup-worker-prebuild

on: [push]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        build:
          - os: ubuntu-20.04
            cc: gcc
            cxx: g++
        node:
          - 18

    runs-on: ${{ matrix.build.os }}

    env:
      CC: ${{ matrix.build.cc }}
      CXX: ${{ matrix.build.cxx }}
      MEDIASOUP_SKIP_WORKER_PREBUILT_DOWNLOAD: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # We need to install some NPM production deps for npm-scripts.js to work.
      - run: npm ci --ignore-scripts --omit=dev
      - run: npm run worker:build
      # Publish prebuild binaries on tag.
      - run: npm run worker:prebuild
      - name: Upload mediasoup-worker prebuilt binary
        uses: softprops/action-gh-release@v1
        with:
          files: worker/prebuild/mediasoup-worker-*.tgz
