name: mediasoup-worker-prebuild

on:
  push:
    tags:
      - "*.*.*"

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        build:
          - os: ubuntu-22.04
          - os: macos-12
          - os: windows-2022

        node:
          - 16

    runs-on: ${{ matrix.build.os }}

    env:
      CC: ${{ matrix.build.cc }}
      CXX: ${{ matrix.build.cxx }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - run: npm run worker:build
      - run: npm run test:worker
        # TODO: Maybe fix this one day.
        if: runner.os != 'Windows'
      # Publish prebuild binaries on tag.
      - run: npm run worker:tar
      - name: Upload mediasoup-worker tar
        uses: softprops/action-gh-release@v1
        with:
          files: worker/prebuild/mediasoup-worker-*.tgz
